"""add tla3bny (LeagueHub) tables

Revision ID: 4d5c00003416
Revises: a7b8c9d0e1f2
Create Date: 2026-07-23 18:19:01.402395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d5c00003416'
down_revision = 'a7b8c9d0e1f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tla3bny_age_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('required_files', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tla3bny_age_categories')),
    sa.UniqueConstraint('label', name=op.f('uq_tla3bny_age_categories_label'))
    )
    op.create_table('tla3bny_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'academy', native_enum=False, length=24), nullable=False),
    sa.Column('status', sa.Enum('active', 'pending', 'approved', 'rejected', native_enum=False, length=24), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('logo_path', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('rejection_reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tla3bny_users'))
    )
    with op.batch_alter_table('tla3bny_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tla3bny_users_email'), ['email'], unique=True)

    op.create_table('tla3bny_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_academy_id', sa.Integer(), nullable=False),
    sa.Column('away_academy_id', sa.Integer(), nullable=False),
    sa.Column('age_category_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.String(length=10), nullable=True),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('num_periods', sa.Integer(), nullable=False),
    sa.Column('max_substitutions', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'live', 'finished', native_enum=False, length=24), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['age_category_id'], ['tla3bny_age_categories.id'], name=op.f('fk_tla3bny_matches_age_category_id_tla3bny_age_categories')),
    sa.ForeignKeyConstraint(['away_academy_id'], ['tla3bny_users.id'], name=op.f('fk_tla3bny_matches_away_academy_id_tla3bny_users')),
    sa.ForeignKeyConstraint(['home_academy_id'], ['tla3bny_users.id'], name=op.f('fk_tla3bny_matches_home_academy_id_tla3bny_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tla3bny_matches'))
    )
    op.create_table('tla3bny_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academy_id', sa.Integer(), nullable=False),
    sa.Column('age_category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('sub_position', sa.String(length=50), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('photo_path', sa.String(length=512), nullable=True),
    sa.Column('papers_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', native_enum=False, length=24), nullable=False),
    sa.Column('rejection_reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['tla3bny_users.id'], name=op.f('fk_tla3bny_players_academy_id_tla3bny_users')),
    sa.ForeignKeyConstraint(['age_category_id'], ['tla3bny_age_categories.id'], name=op.f('fk_tla3bny_players_age_category_id_tla3bny_age_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tla3bny_players'))
    )
    op.create_table('tla3bny_lineups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('academy_id', sa.Integer(), nullable=False),
    sa.Column('formation', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['tla3bny_users.id'], name=op.f('fk_tla3bny_lineups_academy_id_tla3bny_users')),
    sa.ForeignKeyConstraint(['match_id'], ['tla3bny_matches.id'], name=op.f('fk_tla3bny_lineups_match_id_tla3bny_matches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tla3bny_lineups')),
    sa.UniqueConstraint('match_id', 'academy_id', name='uq_tla3bny_lineup_match_academy')
    )
    op.create_table('tla3bny_match_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_academy_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('goal', 'assist', 'yellow', 'red', 'substitution_in', 'substitution_out', native_enum=False, length=24), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('related_event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['tla3bny_matches.id'], name=op.f('fk_tla3bny_match_events_match_id_tla3bny_matches')),
    sa.ForeignKeyConstraint(['player_id'], ['tla3bny_players.id'], name=op.f('fk_tla3bny_match_events_player_id_tla3bny_players')),
    sa.ForeignKeyConstraint(['related_event_id'], ['tla3bny_match_events.id'], name=op.f('fk_tla3bny_match_events_related_event_id_tla3bny_match_events')),
    sa.ForeignKeyConstraint(['team_academy_id'], ['tla3bny_users.id'], name=op.f('fk_tla3bny_match_events_team_academy_id_tla3bny_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tla3bny_match_events'))
    )
    op.create_table('tla3bny_player_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['tla3bny_players.id'], name=op.f('fk_tla3bny_player_files_player_id_tla3bny_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tla3bny_player_files'))
    )
    op.create_table('tla3bny_lineup_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lineup_id', sa.Integer(), nullable=False),
    sa.Column('position_slot', sa.String(length=20), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('is_substitute', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lineup_id'], ['tla3bny_lineups.id'], name=op.f('fk_tla3bny_lineup_slots_lineup_id_tla3bny_lineups')),
    sa.ForeignKeyConstraint(['player_id'], ['tla3bny_players.id'], name=op.f('fk_tla3bny_lineup_slots_player_id_tla3bny_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tla3bny_lineup_slots'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tla3bny_lineup_slots')
    op.drop_table('tla3bny_player_files')
    op.drop_table('tla3bny_match_events')
    op.drop_table('tla3bny_lineups')
    op.drop_table('tla3bny_players')
    op.drop_table('tla3bny_matches')
    with op.batch_alter_table('tla3bny_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tla3bny_users_email'))

    op.drop_table('tla3bny_users')
    op.drop_table('tla3bny_age_categories')
    # ### end Alembic commands ###
