"""initial schema

Revision ID: d478974a3aab
Revises: 
Create Date: 2026-07-17 20:41:42.963189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd478974a3aab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.Enum('superadmin', 'editor', 'clerk', native_enum=False, length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users')),
    sa.UniqueConstraint('username', name=op.f('uq_admin_users_username'))
    )
    op.create_table('ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('image', sa.String(length=512), nullable=True),
    sa.Column('youtube_video', sa.String(length=512), nullable=True),
    sa.Column('facebook_link', sa.String(length=512), nullable=True),
    sa.Column('mobile_number', sa.String(length=40), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=40), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('location_url', sa.String(length=512), nullable=True),
    sa.Column('expire_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ads'))
    )
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.create_index('ix_ads_expire', ['expire_date'], unique=False)

    op.create_table('age_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=80), nullable=True),
    sa.Column('name_ar', sa.String(length=80), nullable=True),
    sa.Column('oldest_birth_year', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_age_groups'))
    )
    op.create_table('app_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('version_code', sa.String(length=20), nullable=False),
    sa.Column('version_name', sa.String(length=40), nullable=False),
    sa.Column('force_update', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_versions')),
    sa.UniqueConstraint('platform', name='uq_app_version_platform')
    )
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=160), nullable=True),
    sa.Column('name_ar', sa.String(length=160), nullable=True),
    sa.Column('city_en', sa.String(length=120), nullable=True),
    sa.Column('city_ar', sa.String(length=120), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('website_url', sa.String(length=512), nullable=True),
    sa.Column('facebook_url', sa.String(length=512), nullable=True),
    sa.Column('instagram_url', sa.String(length=512), nullable=True),
    sa.Column('twitter_url', sa.String(length=512), nullable=True),
    sa.Column('youtube_url', sa.String(length=512), nullable=True),
    sa.Column('established', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clubs'))
    )
    op.create_table('coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name_en', sa.String(length=160), nullable=True),
    sa.Column('full_name_ar', sa.String(length=160), nullable=True),
    sa.Column('birth_year', sa.SmallInteger(), nullable=True),
    sa.Column('nationality_en', sa.String(length=80), nullable=True),
    sa.Column('nationality_ar', sa.String(length=80), nullable=True),
    sa.Column('profile_pic_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coaches'))
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=True),
    sa.Column('title_ar', sa.String(length=255), nullable=True),
    sa.Column('details_en', sa.Text(), nullable=True),
    sa.Column('details_ar', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news'))
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index('ix_news_date', ['date'], unique=False)

    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name_en', sa.String(length=160), nullable=True),
    sa.Column('full_name_ar', sa.String(length=160), nullable=True),
    sa.Column('birth_year', sa.SmallInteger(), nullable=False),
    sa.Column('birth_year_verified', sa.Boolean(), nullable=False),
    sa.Column('full_dob', sa.Date(), nullable=True),
    sa.Column('nationality_en', sa.String(length=80), nullable=True),
    sa.Column('nationality_ar', sa.String(length=80), nullable=True),
    sa.Column('position_en', sa.String(length=60), nullable=True),
    sa.Column('position_ar', sa.String(length=60), nullable=True),
    sa.Column('height_cm', sa.SmallInteger(), nullable=True),
    sa.Column('weight_kg', sa.SmallInteger(), nullable=True),
    sa.Column('preferred_foot', sa.Enum('left', 'right', 'both', native_enum=False, length=24), nullable=True),
    sa.Column('profile_pic_url', sa.String(length=512), nullable=True),
    sa.Column('registration_number', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players'))
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index('ix_players_birth_year', ['birth_year'], unique=False)
        batch_op.create_index('ix_players_name_ar', ['full_name_ar'], unique=False)
        batch_op.create_index('ix_players_name_en', ['full_name_en'], unique=False)

    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=80), nullable=True),
    sa.Column('name_ar', sa.String(length=80), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_seasons_ck_season_dates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seasons'))
    )
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.create_index('ix_seasons_is_active', ['is_active'], unique=False)

    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=160), nullable=True),
    sa.Column('name_ar', sa.String(length=160), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venues'))
    )
    op.create_table('club_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('role_en', sa.String(length=80), nullable=True),
    sa.Column('role_ar', sa.String(length=80), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('start_date IS NULL OR end_date IS NULL OR end_date >= start_date', name=op.f('ck_club_staff_ck_club_staff_dates')),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_staff_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], name=op.f('fk_club_staff_coach_id_coaches'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_staff'))
    )
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('age_group_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('name_en', sa.String(length=160), nullable=True),
    sa.Column('name_ar', sa.String(length=160), nullable=True),
    sa.Column('sector_en', sa.String(length=120), nullable=True),
    sa.Column('sector_ar', sa.String(length=120), nullable=True),
    sa.Column('sector_key', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['age_group_id'], ['age_groups.id'], name=op.f('fk_competitions_age_group_id_age_groups'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_competitions_season_id_seasons'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitions')),
    sa.UniqueConstraint('season_id', 'code', 'age_group_id', 'sector_key', name='uq_competition')
    )
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.create_index('ix_competitions_code', ['code'], unique=False)
        batch_op.create_index('ix_competitions_season', ['season_id'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('age_group_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=160), nullable=True),
    sa.Column('name_ar', sa.String(length=160), nullable=True),
    sa.Column('short_name_en', sa.String(length=40), nullable=True),
    sa.Column('short_name_ar', sa.String(length=40), nullable=True),
    sa.Column('point_deduction', sa.SmallInteger(), nullable=False),
    sa.Column('source_ref', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('point_deduction >= 0', name=op.f('ck_teams_ck_team_point_deduction')),
    sa.ForeignKeyConstraint(['age_group_id'], ['age_groups.id'], name=op.f('fk_teams_age_group_id_age_groups'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_teams_club_id_clubs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_teams_season_id_seasons'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('source_ref', name=op.f('uq_teams_source_ref'))
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index('ix_teams_club_age_season', ['club_id', 'age_group_id', 'season_id'], unique=False)

    op.create_table('competition_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], name=op.f('fk_competition_teams_competition_id_competitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_competition_teams_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competition_teams')),
    sa.UniqueConstraint('competition_id', 'team_id', name='uq_competition_team')
    )
    with op.batch_alter_table('competition_teams', schema=None) as batch_op:
        batch_op.create_index('ix_competition_teams_team', ['team_id'], unique=False)

    op.create_table('player_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('shirt_number', sa.SmallInteger(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'transferred', 'loaned', native_enum=False, length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name=op.f('ck_player_teams_ck_player_team_dates')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_teams_player_id_players'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_player_teams_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_teams'))
    )
    with op.batch_alter_table('player_teams', schema=None) as batch_op:
        batch_op.create_index('ix_player_teams_player', ['player_id'], unique=False)
        batch_op.create_index('ix_player_teams_team', ['team_id'], unique=False)

    op.create_table('stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=True),
    sa.Column('name_ar', sa.String(length=120), nullable=True),
    sa.Column('stage_order', sa.SmallInteger(), nullable=False),
    sa.Column('type', sa.Enum('group', 'league', 'knockout', native_enum=False, length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], name=op.f('fk_stages_competition_id_competitions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stages')),
    sa.UniqueConstraint('competition_id', 'stage_order', name='uq_stage_order')
    )
    op.create_table('team_coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('role_en', sa.String(length=80), nullable=True),
    sa.Column('role_ar', sa.String(length=80), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name=op.f('ck_team_coaches_ck_team_coach_dates')),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], name=op.f('fk_team_coaches_coach_id_coaches'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_coaches_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_coaches'))
    )
    with op.batch_alter_table('team_coaches', schema=None) as batch_op:
        batch_op.create_index('ix_team_coaches_team', ['team_id'], unique=False)

    op.create_table('competition_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=80), nullable=True),
    sa.Column('name_ar', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], name=op.f('fk_competition_groups_stage_id_stages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competition_groups'))
    )
    with op.batch_alter_table('competition_groups', schema=None) as batch_op:
        batch_op.create_index('ix_groups_stage', ['stage_id'], unique=False)

    op.create_table('group_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['competition_groups.id'], name=op.f('fk_group_teams_group_id_competition_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_group_teams_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_teams')),
    sa.UniqueConstraint('group_id', 'team_id', name='uq_group_team')
    )
    with op.batch_alter_table('group_teams', schema=None) as batch_op:
        batch_op.create_index('ix_group_teams_team', ['team_id'], unique=False)

    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('match_date', sa.DateTime(), nullable=False),
    sa.Column('week', sa.String(length=40), nullable=True),
    sa.Column('round_label_en', sa.String(length=120), nullable=True),
    sa.Column('round_label_ar', sa.String(length=120), nullable=True),
    sa.Column('source_ref', sa.String(length=120), nullable=True),
    sa.Column('venue_en', sa.String(length=160), nullable=True),
    sa.Column('venue_ar', sa.String(length=160), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'live', 'completed', 'postponed', 'cancelled', native_enum=False, length=24), nullable=False),
    sa.Column('home_score', sa.SmallInteger(), nullable=True),
    sa.Column('away_score', sa.SmallInteger(), nullable=True),
    sa.Column('home_penalty_score', sa.SmallInteger(), nullable=True),
    sa.Column('away_penalty_score', sa.SmallInteger(), nullable=True),
    sa.Column('referee_main', sa.String(length=120), nullable=True),
    sa.Column('referee_assistant_1', sa.String(length=120), nullable=True),
    sa.Column('referee_assistant_2', sa.String(length=120), nullable=True),
    sa.Column('referee_fourth', sa.String(length=120), nullable=True),
    sa.Column('note_en', sa.String(length=255), nullable=True),
    sa.Column('note_ar', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('home_team_id <> away_team_id', name=op.f('ck_matches_ck_match_teams_differ')),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], name=op.f('fk_matches_away_team_id_teams'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['competition_groups.id'], name=op.f('fk_matches_group_id_competition_groups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], name=op.f('fk_matches_home_team_id_teams'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], name=op.f('fk_matches_stage_id_stages'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_matches_venue_id_venues'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches')),
    sa.UniqueConstraint('source_ref', name=op.f('uq_matches_source_ref'))
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index('ix_matches_away', ['away_team_id'], unique=False)
        batch_op.create_index('ix_matches_date', ['match_date'], unique=False)
        batch_op.create_index('ix_matches_group', ['group_id'], unique=False)
        batch_op.create_index('ix_matches_home', ['home_team_id'], unique=False)
        batch_op.create_index('ix_matches_stage', ['stage_id'], unique=False)
        batch_op.create_index('ix_matches_status', ['status'], unique=False)

    op.create_table('match_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('card_type', sa.Enum('yellow', 'second_yellow', 'red', native_enum=False, length=24), nullable=False),
    sa.Column('minute', sa.SmallInteger(), nullable=True),
    sa.Column('is_extra_time', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_match_cards_match_id_matches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_match_cards_player_id_players'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_match_cards_team_id_teams'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_cards'))
    )
    with op.batch_alter_table('match_cards', schema=None) as batch_op:
        batch_op.create_index('ix_match_cards_match', ['match_id'], unique=False)
        batch_op.create_index('ix_match_cards_player', ['player_id'], unique=False)

    op.create_table('match_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('scorer_id', sa.Integer(), nullable=False),
    sa.Column('assist_id', sa.Integer(), nullable=True),
    sa.Column('minute', sa.SmallInteger(), nullable=True),
    sa.Column('is_extra_time', sa.Boolean(), nullable=False),
    sa.Column('is_own_goal', sa.Boolean(), nullable=False),
    sa.Column('is_penalty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    # NOTE: no CHECK "assist_id <> scorer_id" here — MySQL (err 3823) forbids a
    # CHECK on a column that an FK references with ON DELETE SET NULL. The rule
    # is enforced in the data-entry code instead. See app/models/match.py.
    sa.ForeignKeyConstraint(['assist_id'], ['players.id'], name=op.f('fk_match_goals_assist_id_players'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_match_goals_match_id_matches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scorer_id'], ['players.id'], name=op.f('fk_match_goals_scorer_id_players'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_match_goals_team_id_teams'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_goals'))
    )
    with op.batch_alter_table('match_goals', schema=None) as batch_op:
        batch_op.create_index('ix_match_goals_assist', ['assist_id'], unique=False)
        batch_op.create_index('ix_match_goals_match', ['match_id'], unique=False)
        batch_op.create_index('ix_match_goals_scorer', ['scorer_id'], unique=False)

    op.create_table('match_penalty_shootouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('kick_order', sa.SmallInteger(), nullable=False),
    sa.Column('result', sa.Enum('scored', 'missed', 'saved', 'off_target', native_enum=False, length=24), nullable=False),
    sa.Column('is_winning_kick', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_match_penalty_shootouts_match_id_matches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_match_penalty_shootouts_player_id_players'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_match_penalty_shootouts_team_id_teams'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_penalty_shootouts')),
    sa.UniqueConstraint('match_id', 'team_id', 'kick_order', name='uq_shootout_kick')
    )
    with op.batch_alter_table('match_penalty_shootouts', schema=None) as batch_op:
        batch_op.create_index('ix_shootout_match', ['match_id'], unique=False)

    op.create_table('match_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('jersey_number', sa.SmallInteger(), nullable=True),
    sa.Column('position', sa.Enum('GK', 'RB', 'LB', 'CB', 'CDM', 'CM', 'CAM', 'RM', 'LM', 'RW', 'LW', 'ST', 'CF', native_enum=False, length=8), nullable=True),
    sa.Column('is_starter', sa.Boolean(), nullable=False),
    sa.Column('minutes_played', sa.SmallInteger(), nullable=False),
    sa.Column('goals', sa.SmallInteger(), nullable=False),
    sa.Column('assists', sa.SmallInteger(), nullable=False),
    sa.Column('yellow_cards', sa.SmallInteger(), nullable=False),
    sa.Column('red_cards', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_match_players_match_id_matches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_match_players_player_id_players'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_match_players_team_id_teams'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_players')),
    sa.UniqueConstraint('match_id', 'player_id', name='uq_match_player')
    )
    with op.batch_alter_table('match_players', schema=None) as batch_op:
        batch_op.create_index('ix_match_players_player', ['player_id'], unique=False)
        batch_op.create_index('ix_match_players_team', ['team_id'], unique=False)

    op.create_table('match_substitutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_out_id', sa.Integer(), nullable=False),
    sa.Column('player_in_id', sa.Integer(), nullable=False),
    sa.Column('minute', sa.SmallInteger(), nullable=True),
    sa.Column('is_extra_time', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('player_out_id <> player_in_id', name=op.f('ck_match_substitutions_ck_sub_players_differ')),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_match_substitutions_match_id_matches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_in_id'], ['players.id'], name=op.f('fk_match_substitutions_player_in_id_players'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['player_out_id'], ['players.id'], name=op.f('fk_match_substitutions_player_out_id_players'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_match_substitutions_team_id_teams'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_substitutions'))
    )
    with op.batch_alter_table('match_substitutions', schema=None) as batch_op:
        batch_op.create_index('ix_match_subs_match', ['match_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_substitutions', schema=None) as batch_op:
        batch_op.drop_index('ix_match_subs_match')

    op.drop_table('match_substitutions')
    with op.batch_alter_table('match_players', schema=None) as batch_op:
        batch_op.drop_index('ix_match_players_team')
        batch_op.drop_index('ix_match_players_player')

    op.drop_table('match_players')
    with op.batch_alter_table('match_penalty_shootouts', schema=None) as batch_op:
        batch_op.drop_index('ix_shootout_match')

    op.drop_table('match_penalty_shootouts')
    with op.batch_alter_table('match_goals', schema=None) as batch_op:
        batch_op.drop_index('ix_match_goals_scorer')
        batch_op.drop_index('ix_match_goals_match')
        batch_op.drop_index('ix_match_goals_assist')

    op.drop_table('match_goals')
    with op.batch_alter_table('match_cards', schema=None) as batch_op:
        batch_op.drop_index('ix_match_cards_player')
        batch_op.drop_index('ix_match_cards_match')

    op.drop_table('match_cards')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index('ix_matches_status')
        batch_op.drop_index('ix_matches_stage')
        batch_op.drop_index('ix_matches_home')
        batch_op.drop_index('ix_matches_group')
        batch_op.drop_index('ix_matches_date')
        batch_op.drop_index('ix_matches_away')

    op.drop_table('matches')
    with op.batch_alter_table('group_teams', schema=None) as batch_op:
        batch_op.drop_index('ix_group_teams_team')

    op.drop_table('group_teams')
    with op.batch_alter_table('competition_groups', schema=None) as batch_op:
        batch_op.drop_index('ix_groups_stage')

    op.drop_table('competition_groups')
    with op.batch_alter_table('team_coaches', schema=None) as batch_op:
        batch_op.drop_index('ix_team_coaches_team')

    op.drop_table('team_coaches')
    op.drop_table('stages')
    with op.batch_alter_table('player_teams', schema=None) as batch_op:
        batch_op.drop_index('ix_player_teams_team')
        batch_op.drop_index('ix_player_teams_player')

    op.drop_table('player_teams')
    with op.batch_alter_table('competition_teams', schema=None) as batch_op:
        batch_op.drop_index('ix_competition_teams_team')

    op.drop_table('competition_teams')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index('ix_teams_club_age_season')

    op.drop_table('teams')
    with op.batch_alter_table('competitions', schema=None) as batch_op:
        batch_op.drop_index('ix_competitions_season')
        batch_op.drop_index('ix_competitions_code')

    op.drop_table('competitions')
    op.drop_table('club_staff')
    op.drop_table('venues')
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_index('ix_seasons_is_active')

    op.drop_table('seasons')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index('ix_players_name_en')
        batch_op.drop_index('ix_players_name_ar')
        batch_op.drop_index('ix_players_birth_year')

    op.drop_table('players')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index('ix_news_date')

    op.drop_table('news')
    op.drop_table('coaches')
    op.drop_table('clubs')
    op.drop_table('app_versions')
    op.drop_table('age_groups')
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.drop_index('ix_ads_expire')

    op.drop_table('ads')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
